### ISSUE TITLE
Giúp tôi với ông

### ISSUE THREAD

**Issue by hoangxuanlam2007** [khanh3118/tftactics1022#2]
- Ông ơi tôi có đọc qua cái source code của ông nhưng mà vẫn chưa hiểu ông lấy champion từ đâu. Nếu mà call api thì ông cho tôi xin cái api để tìm hiểu với.
- Nếu có fb hay j cho tui xin để dễ hỏi ^^

**Comment by khanh3118** [comment]
tôi lưu data trên firebase.

**Comment by khanh3118** [comment]
gọi api trong thư mục src/firebase

**Comment by hoangxuanlam2007** [comment]
> gọi api trong thư mục src/firebase

Tôi biết á ông, ông có fb ko z.
Tôi bt ông dùng firebase nma tôi ko bt dc cái data ông lưu là j ý, nên tôi cx tạo 1 cái firestore thử xong r cho champion_name, champion_origin,... cũng mò từng string một nma toàn bị báo lỗi ý ông. Bây giờ tôi cx muốn update cái source của ông lên set 8.5 nma bh mà làm lại từ đầu thì lâu lắm, cái code của ông nó mặc định sẵn với cái string của ông lưu trên firebase rồi.
So... nếu có thể thì ông có thể share tôi cái api đấy dc ko? Tôi muốn xem cách ông store các giá trị trong firebase, ông xếp như nào (array, string, number,...). Có gì ông kb fb tôi với: https://facebook.com/ch1mmm

> À mà ông đang bị lộ api key ở trong ./firebase/main.js 
> Tôi khuyên ông nên tạo 1 cái file để store cái 'api_key' sau đó tạo '.gitignore' chứ như tôi thấy tôi có api của ông r thì call lúc nào cx dc ý trời, dễ sập lắm, nên tôi bảo ông z. Cũng mong ông share cho tôi 1 chút để tôi viết lại cho cái set 8.5 mới này, nếu có j thì thôi sẽ cải thiện hơn, ông yên tâm tôi sẽ credit đầy đủ ^^

**Comment by khanh3118** [comment]
![champion1](https://user-images.githubusercontent.com/82632380/233819670-8869ce88-221c-48fa-bd18-a3f75c990b3c.png)
![champion2](https://user-images.githubusercontent.com/82632380/233819672-716f3dde-c425-4c3d-a6d7-23f761a3dbbf.png)
![champion3](https://user-images.githubusercontent.com/82632380/233819673-6203405c-972d-4e1d-84f2-e7dbc181fb3c.png)
![item](https://user-images.githubusercontent.com/82632380/233819674-a8361e51-11d7-4127-a06d-35332e674d2d.png)
![synergy](https://user-images.githubusercontent.com/82632380/233819675-8be6ece8-0c28-49d2-9e03-464010695192.png)

**Comment by khanh3118** [comment]
champion
![champion1](https://user-images.githubusercontent.com/82632380/233819690-40e3a59d-5ab8-4d35-a50c-a29046b646ba.png)
![champion2](https://user-images.githubusercontent.com/82632380/233819692-bf977025-8f1b-44c8-84c7-384308176a9e.png)
![champion3](https://user-images.githubusercontent.com/82632380/233819693-f9d0d783-ca71-4ebf-90e6-b70c1f2b8043.png)

**Comment by khanh3118** [comment]
item
![item](https://user-images.githubusercontent.com/82632380/233819698-4267bb1c-d56f-45bd-8de5-75930081085d.png)

**Comment by khanh3118** [comment]
trait
![synergy](https://user-images.githubusercontent.com/82632380/233819715-fb8fe7b4-99ec-4827-b37d-730c04119039.png)

**Comment by khanh3118** [comment]
api k sao đâu ô, t làm cho vui thôi, call hết data thì mai lại có k sập được. mà chắc k ai rảnh mà đi phá trang của t làm j

**Comment by khanh3118** [comment]
lưu trên firebase nếu dùng hết data hôm nay thì mai lại có lại, mà chắc k ai phá đâu ô

**Comment by hoangxuanlam2007** [comment]
thankss

**Comment by hoangxuanlam2007** [comment]
> lưu trên firebase nếu dùng hết data hôm nay thì mai lại có lại, mà chắc k ai phá đâu ô

Cảm ơn ông vì đã rep tôi. Tôi có thể xin thêm ảnh firebase về phần Team comps dc ko? Cả phần items hoàn chỉnh (được ghép bởi 2 trang bị), aura items, unique items nữa ^^

**Comment by hoangxuanlam2007** [comment]
À cả phần meta report nữa, hnhu ông có lưu ở herokuapp nma lỗi mất r

**Comment by khanh3118** [comment]
> > lưu trên firebase nếu dùng hết data hôm nay thì mai lại có lại, mà chắc k ai phá đâu ô
> 
> Cảm ơn ông vì đã rep tôi. Tôi có thể xin thêm ảnh firebase về phần Team comps dc ko, tôi muốn xem ông tạo những cái đội hình và trang bị đồ kiểu gì. Còn phần filter ở team comps, tôi vẫn ko biết ông lưu cái playstyle ở đâu

![image](https://user-images.githubusercontent.com/82632380/236484309-4942998f-338b-4bb7-ba83-3e776c9b499c.png)

**Comment by khanh3118** [comment]
> À cả phần meta report nữa, hnhu ông có lưu ở herokuapp nma lỗi mất r

heroku bắt đầu thu phí r k cho free nữa nên api phần đấy hư r ô

**Comment by hoangxuanlam2007** [comment]
> > À cả phần meta report nữa, hnhu ông có lưu ở herokuapp nma lỗi mất r
> 
> heroku bắt đầu thu phí r k cho free nữa nên api phần đấy hư r ô

tysm bro, ông giúp tôi nhiều quá tôi cũng ngại .-.
so... tui cần xem ông tạo cái team comps kiểu gì á :v tại tôi thấy phần teamcomp nó vẫn hđ :vv
và ý tôi là cái playstyle ông tạo kiểu gì ý, làm sao để mỗi cái team comp có 1 cái style riêng thì tui cần xem phần đó ^^

**Comment by hoangxuanlam2007** [comment]
mà ông ơi ông cho tui tên collection dc ko?
kiểu này á:
![image](https://user-images.githubusercontent.com/89345805/236671329-36fed6e9-59a4-49bf-91e8-6185a4fd1a6c.png)

Tôi còn thử lại với `synergys` và `traits`:
![image](https://user-images.githubusercontent.com/89345805/236671411-5ace332b-35e0-46af-a879-c0182ceb4c26.png)


Vì thực sự tôi làm y như trong ảnh ông gửi mà nó toàn lỗi:

```
Unhandled Thrown Error!
Cannot read properties of undefined (reading 'synergy_name')
TypeError: Cannot read properties of undefined (reading 'synergy_name')
    at http://localhost:3000/static/js/bundle.js:1769:97
    at Array.filter (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:1769:39
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:76592:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:79474:24)
    at updateSimpleMemoComponent (http://localhost:3000/static/js/bundle.js:79336:14)
    at updateMemoComponent (http://localhost:3000/static/js/bundle.js:79209:18)
    at beginWork (http://localhost:3000/static/js/bundle.js:81239:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:86137:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:85406:16)
```

**Comment by khanh3118** [comment]
> mà ông ơi ông cho tui tên all collection dc ko? Với lại toàn bộ data trong collection đó (ngoài 3 cái ông cho r thì tôi cần phần teamcomps) Nó cứ báo lỗi vì toàn bộ data trên firebase chưa có hết ý nên nhiều cái bị `undefined` kiểu này á: ![image](https://user-images.githubusercontent.com/89345805/236673525-8747dc1b-7ea7-4288-8c7d-d452f416a869.png)

![image](https://github.com/khanh3118/tftactics1022/assets/82632380/1bebcedd-4180-4e2d-b79d-b0e401b7d46a)
![image](https://github.com/khanh3118/tftactics1022/assets/82632380/caca29fb-21b4-4b7f-8d67-f80d9b2eb80e)
![image](https://github.com/khanh3118/tftactics1022/assets/82632380/2fe5e03b-d5d8-4b22-97a8-97497b19947e)
![image](https://github.com/khanh3118/tftactics1022/assets/82632380/1403490f-31bd-47ee-a5f2-3587c8c99c86)
![image](https://github.com/khanh3118/tftactics1022/assets/82632380/072cb7eb-556e-496f-a490-4f0185cc1bfe)
![image](https://github.com/khanh3118/tftactics1022/assets/82632380/77a3f7d5-455b-40a8-9afe-6ac8a09cce03)

**Comment by khanh3118** [comment]
sr ô vì reb chậm tại t đi làm nên không có nhiều thời gian.
thật ra project này t làm cho vui thôi, trình cũng gà nên còn nhiều sai sót, nhưng mà t rất thích thể loại web kéo thả về game ntn, nếu ô thích ô có thể join project cùng tôi, còn một số cái t chưa làm như tìm thông tin người chơi giống của dtcl.gg, patch note, tier list
t cũng muốn chuyển từ styled component sang dùng tailwindcss cho code gọn hơn nên nếu muốn join thì nói nhé, k thiếu việc đâu :v
t vừa update lên mùa 8.5 rồi và vẫn giữ data mùa cũ https://tftactics-gg-2.web.app/teamcomps (chuyển mùa bằng cách select trên góc trái)
về phần tạo api thì tôi copy trên trang tftactics-gg trong code có phần manager đấy nếu ô có tg thì ngồi đánh từng item từng con tướng vào cũng k nhiều lắm đâu

**Comment by khanh3118** [comment]
nếu ô muốn tự làm data thì trong code có phần manager đấy, nếu có tg ô ngồi đánh từng con tướng vào cũng được không nhiều lắm đâu

**Comment by hoangxuanlam2007** [comment]
À oke nma ông có fb ko tui kb có j hỏi cho nhanh ^^

**Comment by hoangxuanlam2007** [comment]
À phần teambuilders có gì thế ông :v 
Tôi viết tạm mấy cái vô mà nó cứ undefined cái champion_img_link

**Comment by khanh3118** [comment]
> À phần teambuilders có gì thế ông :v Tôi viết tạm mấy cái vô mà nó cứ undefined cái champion_img_link

ô chạy code của t lên rồi log ra là thấy

**Comment by khanh3118** [comment]
> À phần teambuilders có gì thế ông :v Tôi viết tạm mấy cái vô mà nó cứ undefined cái champion_img_link

![image](https://github.com/khanh3118/tftactics1022/assets/82632380/bd362966-d096-46f6-855f-0bcb5e860a08)
như này thôi

**Comment by khanh3118** [comment]
> À phần teambuilders có gì thế ông :v Tôi viết tạm mấy cái vô mà nó cứ undefined cái champion_img_link

![image](https://github.com/khanh3118/tftactics1022/assets/82632380/4aaa9444-3e89-44c5-868d-57ecf886399b)
